# R for travis: https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false

r:
  - 3.6
  - release
  - devel
  - bioc-release

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
